DORSEY, G. A. and KROEBER, A. L. Traditions of the Arapaho. Field Columbian Museum, Anthropological Series, Chicago, 1903, Vol. 5. (50-52) Available at Internet Archive. https://archive.org/details/traditionsofarap05dors


16. Nih’ançan loses his eyes

Nih’ançan went down the river and met a man who was in the act of throwing his eyes up in the cottonwood tree-tops, and he was very much interested in him. Nih’ançan went to this man weeping for mercy, and saying, "I come to you that I may be taught of you how to perform your wonderful trick." "Oh! You are smart enough! What more do, you want ?" said the man. "Well, you see I like your way and want to follow your footsteps," said Nih’ançan. Finally the man consented and showed him. This man stepped off and said, "Let my eyes light on the branches." Then his eyes would go from him and light in the tree-top. ''Well. Nih’ançan, that is the way you must do, but not excessively," said the man. Then the man said, when the eyes were up in the tree, "Let my eyes come back," and sure enough, they returned to him. 

This man went away, and Nih’ançan went in a different direction. Nih’ançan came to a bunch of cottonwood trees and did as the man had done. Now Nih’ançan was instructed not to do this trick unless it was necessary. Nih’ançan being successful in the trick went away very proudly and came to a second bunch of cottonwood trees and commanded his eyes to light on the tree-top, and they did so. Then he commanded them and they returned to their sockets. This made Nih’ançan very proud, and a third time he attempted to exercise the power which had been given him.

While he was hunting something in the tall grass, he came to a big grove of cottonwood trees, and stopping, commanded his eyes to go to the top of the cottonwood trees, saying, "Let my eyes beat the top of the trees, fastened to the branches," and it was so. His eyes were hanging entirely separated from him. "Well ! Now let my eyes return!" said Nih’ançan, but they did not return. "Let my eyes return!" said he, but they were still up in the tree. "Let my eyes come down!'' said he again, but still they were up in the tree, waving like small balls. Again he cried out with a long, continuous cry, but his eyes still remained in the tree. Then he called repeatedly, but without avail. So he started off toward the river without any eyes, to get a drink. He was feeling around as he went, and finally touched the willows and kept agoing until he came to the bank of the river close to the timber, where he heard animals running by him—mice, rats and rabbits. "Say, partner," said he to the mouse, "loan me your eyes!" So the mouse loaned him his eyes; but they proved too small and would not stay in the sockets, and besides he could not see anything with them. So he gave them back to the mouse and went from one animal 'to another. borrowing their eyes, until at last he ran across the owl. ''Say, partner," said Nih’ançan, "Loan me your eyes!" The owl loaned him his eyes, and from that time on, he has always had the yellow eyes. But Nih’ançan’s eyes still hung to the tree-top and are now seen at all seasons of the year on the bark and branches of the cottonwood.-D.

Told by Found. Cf. No. 17 [below]. This widespread tale is found, in addition to the tribes mentioned in the notes to No. 17, among the Pawnee, Arikara, and Osage.
 
17.  Nih’ançan loses his eyes

Nih’ançan was traveling again. He came to the thick timber along a stream, and heard something crying repeatedly: Çançankancei!” Having listened, he went towards the noise to see what it was, and peeped secretly. Then he saw a man before an elm tree, and noticed that his eyes were on the tree. The man said : " Çançankancei," and the eyes flew back into his head. Again he said “Çançankancei," and the eyes were on the tree. Thus he kept doing. Nih’ançan wished this power very much. He pretended to be crying, and, coming up to the man, said to him, "I have heard that you are able to cause your eyes to go out and come back, and I want to learn this from you." The man said  "That is no medicine. It is only play." "Well, I want the same play as you," said Nih’ançan. At last he persuaded the man to tell him. The man said : "Say Çançankancei." "Thanks,'' said Nih’ançan, much pleased. "But do not do it too often," said the man. "After you come to that hill over there you may do it as often as you wish. But until you reach it you must do it only four times. Otherwise you will have trouble." Then he loosened Nih’ançan's eyes for him, and Nih’ançan went on his way. Coming to an elm tree, Nih’ançan said "Çançankancei,” and suddenly he was blind. He put his fingers to his eyes and felt only the sockets. "This is fine fun," he said and then, calling the word again, he got his eyes back, being suddenly able to see. Then he was even more pleased. He did the trick four times. Then he wished to continue playing. "Let me try it again," he said. "I have done it four times, and the eyes will surely come back this time." So he said : "Çançankancei," and his eyes flew up into the tree. Then he said ''Çançankancei” again, but his eyes did not come back. He continued to call "Çançankancei" all day until he was hoarse, and was able to say “Çançankancei” only at intervals. 

Meanwhile his eyes had already begun to dry and shrivel. The man who had taught him heard him calling, and passing by, said to him : "So you have lost your eyes. Well, you will not get them back from me." And he went on. Nih’ançan said, whenever he heard any noise, "My brother, is that you ? I think I used to know you, What is your name?" At last a mole came to him and said, “My brother, what do you wish?" Nih’ançan said to him : "Lend me your eyes." And the mole gave them to him. He put the tiny eyes into his sockets and could then just barely see his own eyes on the tree. He climbed up, got his eyes and put them in place again. But the small eyes of the mole he threw away saying, "I care nothing about your eyes. Get them for yourself." And he went his way. That is why the mole is blind.1-K.

(1 From informant B.)
